export * from './about';
export * from './become-tutor';
export * from './contact';
export * from './faq-ticket';
export * from './faq';
export * from './home';
export * from './languages-courses';
export * from './student-success';
export * from './welcome';
