export enum CourseStatus {
  active = 'active',
  pending = 'pending',
  rejected = 'rejected',
  canceled = 'canceled',
  requested = 'requested',
  completed = 'completed',
  inprogress = 'inprogress',
  adminCancelled = 'metutors',
  teacherCancelled = 'teacher',
  studentCancelled = 'student',
  paymentPending = 'payment_pending',
  cancelledByStudent = 'cancelled_by_student',
  cancelledByTeacher = 'cancelled_by_teacher',
  requestedToMetutors = 'requested_to_metutors',
}
