export const DAYS_WEEK = ['Mon', 'Tues', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

export const SORTED_DAYS_WEEK = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday'
];

export const GENDERS = ['Male', 'Female'];

export const COMPUTER_SKILLS = ['Basic', 'Intermediate', 'Expert'];

export const DEGREE_LEVELS = [
  'Associate degree',
  'Bachelor’s degree',
  'Master’s degree',
  'Doctoral degree'
];

export const DEGREE_FIELDS = [
  'Associate of Arts',
  'Associate of Applied Arts',
  'Associate of Engineering',
  'Associate of Science',
  'Associate of General Studies',
  'Associate of Science in Nursing',
  'Associate of Technology',
  'Associate of Applied Business',
  'Associate of Applied Science',
  'Associate of Arts and Sciences',
  'Associate of Arts in Teaching',
  'Associate of Baccalaureate Studies',
  'Associate of Business Administration',
  'Associate of Engineering Science',
  'Associate in Engineering Technology',
  'Associate of Fine Arts',
  'Associate of Pre-Engineering',
  'Associate of Industrial Technology',
  'Associate of Occupational Studies',
  'Associate in Physical Therapy',
  'Associate of Political Science',
  'Associate of Public Service',
  'Bachelor of Architecture',
  'Bachelor of Arts',
  'Bachelor of Applied Arts and Science',
  'Bachelor of Science in Information Technology',
  'Bachelor of Engineering',
  'Bachelor of Science',
  'Bachelor of Science in Biology',
  'Bachelor of Science in Chemistry',
  'Bachelor of Science in Physics',
  'Bachelor of Science in Mathematics',
  'Bachelor of Science in Geology',
  'Bachelor of Science in Data Analytics',
  'Bachelor of Science in Programming',
  'Bachelor of Science in Electrical Engineering',
  'Bachelor of Science in Mechanical Engineering',
  'Bachelor of Science in Computer Engineering',
  'Bachelor of Science in Software Engineering',
  'Bachelor of Science in Chemical Engineering',
  'Bachelor of Science in Petroleum Engineering',
  'Bachelor of Science in Industrial Engineering',
  'Bachelor of Science in Engineering',
  'Bachelor of Science in Aerospace Engineering',
  'Bachelor of Science in Biomedical Engineering',
  'Bachelor of Science in Telecommunication Engineering',
  'Bachelor of Science in Civil Engineering',
  'Bachelor of Science in Mechatronics Engineering',
  'Bachelor of Science in Communication Engineering',
  'Bachelor of Science in Cybersecurity',
  'Bachelor of Engineering Technology',
  'Bachelor of Technology',
  'International Business Economics',
  'Bachelor of Business Administration',
  'Bachelor of Management Studies',
  'Bachelor of Administrative Studies',
  'Bachelor of International Business Economics',
  'Bachelor of Commerce',
  'Bachelor of Fine Arts',
  'Bachelor of Business',
  'Bachelor of Business in Accounting',
  'Bachelor of Business in Finance',
  'Bachelor of Business in Management',
  'Bachelor of Business in Marketing',
  'Bachelor of Literature and Arts',
  'Bachelor of Science in Pharmaceutical',
  'Bachelor of Science in Medicine',
  'Bachelor of Management and Organizational Studies',
  'Bachelor of Business Science',
  'Bachelor of Economics',
  'Bachelor of Arts in Organizational Management',
  'Bachelor of Computer Science',
  'Bachelor of Computer Applications',
  'Bachelor of Business Information Systems',
  'Bachelor of Medical Science',
  'Bachelor of Medical Biology',
  'Bachelor of Science in Public Health',
  'Bachelor of Science in Nursing',
  'Bachelor of Health Science',
  'Bachelor of Arts for Teaching',
  'Bachelor of Aviation',
  'Bachelor of Religious Studies',
  'Bachelor of Film and Television',
  'Bachelor of Journalism',
  'Bachelor of Liberal Arts',
  'Bachelor of General Studies',
  'Bachelor of Science in Human Biology',
  'Bachelor of Applied Studies',
  'Bachelor of Liberal Studies',
  'Bachelor of Professional Studies',
  'Bachelor of Library and Information Science',
  'Bachelor of Art in Music',
  'Bachelor of Arts in Psychology',
  'Bachelor of Science in Education',
  'Bachelor of Applied Science',
  'Bachelor of Science in Law',
  'Bachelor of Social Science',
  'Bachelor of Arts in Social Work',
  'Bachelor of Tourism Studies',
  'Bachelor of Mathematical Sciences',
  'Bachelor of Public Affairs',
  'Bachelor of Urban and Regional Planning',
  'Master of Accountancy',
  'Master of Advanced Study',
  'Master of Economics',
  'Master of Architecture',
  'Master of Applied Science',
  'Master of Arts',
  'Master of Arts in Teaching',
  'Master of Arts in Liberal Studies',
  'Master of Business',
  'Master of Business Administration',
  'Master of Business Informatics',
  'Master of Science',
  'Master of Chemistry',
  'Master of Commerce',
  'Master of Computational Finance',
  'Master of Computer Applications',
  'Master in Creative Technologies',
  'Master of Education',
  'Master of Engineering Management',
  'Master of Finance',
  'Master of Financial Engineering',
  'Master of Financial Economics',
  'Master of Fine Arts',
  'Master of Health Administration',
  'Master of Humanities',
  'Master of International Affairs',
  'Master of International Business',
  'Master of International Studies',
  'Masters in International Economics',
  'Master of Information System Management',
  'Master of Information Technology',
  'Master of Laws',
  'Master of Liberal Arts',
  'Master of Library and Information Science',
  'Master of Management',
  'Master of Mathematics',
  'Master of Medical Science',
  'Master of Occupational Therapy',
  'Master of Pharmacy',
  'Master of Philosophy',
  'Master of Physics',
  'Master of Physician Assistant Studies',
  'Master of Political Science',
  'Master of Professional Studies',
  'Master of Public Administration',
  'Master of Public Affairs',
  'Master of Public Health',
  'Master of Public Management',
  'Master of Religious Education',
  'Master of Research',
  'Master of Science in Education',
  'Master of Science in Engineering',
  'Master of Science in Finance',
  'Master of Science in Human Resource Development',
  'Master of Science in Information Systems Management',
  'Master of Science in Information Systems',
  'Master of Science in Information Technology',
  'Master of Science in Nursing',
  'Master of Science in Project Management',
  'Master of Science in Management',
  'Master of Science in Leadership',
  'Master of Science in Supply Chain Management',
  'Master of Science in Teaching',
  'Master of Social Science',
  'Master of Surgery',
  'Master of Studies',
  'Doctor of Business Administration',
  'Doctor of Engineering',
  'Doctor of Education',
  'Doctor of Fine Arts',
  'Doctor of Musical Arts',
  'Doctor of Music Education',
  'Doctor of Modern Languages',
  'Doctor of Nursing Science',
  'Doctor of Philosophy',
  'Doctor of Public Health',
  'Doctor of Science',
  'Other major of studies'
];

export const DEGREE_FIELDS_AR = [
  'دبلوم آداب',
  'دبلوم آداب تطبيقيه',
  'دبلوم هندسة',
  'دبلوم علوم',
  'دبلوم دراسات عامه',
  'دبلوم علوم في التمريض',
  'دبلوم مشارك في التكنولوجيا',
  'دبلوم أعمال تجارية تطبيقية',
  'دبلوم علوم تطبيقيه',
  'دبلوم آداب وعلوم',
  'دبلوم آداب في التعليم',
  'دبلوم في دراسات البكالوريا',
  'دبلوم إدارة أعمال',
  'دبلوم علوم هندسية',
  'دبلوم تكنولوجيا الهندسة',
  'دبلوم فنون',
  'دبلوم هندسة',
  'دبلوم تكنولوجيا صناعية',
  'دبلوم دراسات مهنية',
  'دبلوم علاج طبيعي',
  'دبلوم علوم سياسية',
  'دبلوم خدمة مجتمع',
  'بكالوريوس هندسة عمارة',
  'بكالوريوس آداب',
  'بكالوريوس فنون تطبيقية وعلوم',
  'بكالوريوس علوم في تكنولوجيا المعلومات',
  'بكالوريوس في الهندسة',
  'بكالوريوس علوم',
  'بكالوريوس علوم في علوم الأحياء',
  'بكالوريوس علوم في الكيمياء',
  'بكالوريوس علوم في الفيزياء',
  'بكالوريوس علوم في الرياضيات',
  'بكالوريوس علوم في علوم الأرض',
  'بكالوريوس علوم في تحليل البيانات',
  'بكالوريوس علوم في برمجة الحاسوب',
  'بكالوريوس علوم في الهندسة الكهربائية',
  'بكالوريوس علوم في الهندسة الميكانيكية',
  'بكالوريوس علوم هندسة الحاسب الالي',
  'بكالوريوس علوم في هندسة البرمجيات',
  'بكالوريوس علوم في الهندسة الكيميائية',
  'بكالوريوس علوم هندسة البترول',
  'بكالوريوس علوم الهندسة الصناعية',
  'بكالوريوس علوم في الهندسة',
  'بكالوريوس علوم في هندسة الطيران',
  'بكالوريوس علوم الهندسة الطبية',
  'بكالوريوس علوم هندسة الاتصالات',
  'بكالوريوس علوم في الهندسة المدنية',
  'بكالوريوس علوم في هندسة الميكاترونكس',
  'بكالوريوس علوم هندسة الإتصالات',
  'بكالوريوس علوم في الأمن السيبرالي',
  'بكالوريوس في تكنولوجيا الهندسة',
  'بكالوريوس في التكنولوجيا',
  'بكالوريوس إقتصاد التجارة الدولية',
  'بكالوريوس إدارة الاعمال',
  'بكالوريوس في الدراسات الإدارية',
  'بكالوريوس في الدراسات الإدارية',
  'بكالوريوس التجارة والاقتصاد الدولية',
  'بكالوريوس في الاعلان',
  'بكالوريوس في الفنون الجميلة',
  'بكالوريوس في التجارة',
  'بكالوريوس تجارة في المحاسبة',
  'بكالوريوس تجارة في المالي',
  'بكالوريوس تجارة في الأدارة',
  '  بكالوريوس تجارة في التسويق',
  'بكالوريوس في الآداب والفنون',
  'بكالوريوس علوم في الصيدلة',
  'بكالوريوس علوم في الطب',
  'بكالوريوس في الدراسات الإدارية والتنظيمية',
  'بكالوريوس العلوم التجارية',
  'بكالوريوس إقتصاد',
  'بكالوريوس الإدارة المؤسسية',
  'بكالوريوس علوم الحاسوب',
  'بكالوريوس في تطبيقات الحاسوب',
  'بكالوريوس في نظم إدارة المعلومات',
  'بكالوريوس علوم طبية',
  'بكالوريوس علم الأحياء الطبية',
  'بكالوريوس علوم في الصحة العامة',
  'بكالوريوس علوم في التمريض',
  'بكالوريوس علوم الصحة',
  'بكالوريوس آداب في التعليم',
  'بكالوريوس في الطيران',
  'بكالوريوس في الدراسات الدينية',
  'بكالوريوس في علوم السينما والتلفزيون',
  'بكالوريوس صحافة',
  'بكالوريوس في الفنون الحرة',
  'بكالوريوس دراسات عامة',
  'بكالوريوس العلوم في علم الأحياء البشري',
  'بكالوريوس العلوم التطبيقية',
  'بكالوريوس دراسات الليبرالية',
  'بكالوريوس في الدراسات المهنية',
  'بكالوريوس علم المكتبات والمعلومات',
  'بكالوريوس آداب في الموسيقى',
  'بكالوريوس آداب في علم النفس',
  'بكالوريوس علوم في التربية والتعليم',
  'بكالوريوس علوم تطبيقية',
  'بكالوريوس علوم القانون',
  'بكالوريوس علم الاجتماع',
  'بكالوريوس خدمة إجتماعية',
  'بكالوريوس الدراسات السياحية',
  'بكالوريوس علوم الرياضيات',
  'بكالوريوس إدارة الشؤون العامة والسياسية',
  'بكالوريوس التخطيط العمراني والإقليمي',
  'ماجستير محاسبة',
  'ماجستير دراسات عليا',
  'ماجستير إقتصاد',
  'ماجستير عمارة',
  'ماجستير علوم تطبيقية',
  'ماجستير آداب',
  'ماجستير آداب في التدريس',
  'ماجستير آداب في الدراسات الليبرالية',
  'ماجستير في تجارة الاعمال',
  'ماجستير إدارة الأعمال',
  'ماجستير في إدارة الاعمال للمعلوماتية',
  'ماجستير في العلوم',
  'ماجستير في الكيمياء',
  'ماجستير في التجارة',
  'ماجستير في التمويل الحاسوبي',
  'ماجستير في تطبيقات الكمبيوتر',
  'ماجستير في التكنولوجيا الإبداعية',
  'ماجستير في التعليم',
  'ماجستير إدارة هندسية',
  'ماجستير مالية',
  'ماجستير هندسة مالية',
  'ماجستير إقتصاد مالي',
  'ماجستير فنون',
  'ماجستير إدارة صحية',
  'ماجستير العلوم الإنسانية',
  'ماجستير علاقات دولية',
  'ماجستير تجارة دولية',
  'ماجستير دراسات دولية',
  'ماجستير إقتصاد دولي',
  'ماجستير إدارة نظم المعلومات',
  'ماجستير تكنولوجيا المعلومات',
  'ماجستير حقوق',
  'ماجستير فنون حرة',
  'ماجستير علم المكتبات والمعلومات',
  'ماجستير أدارة',
  'ماجستير رياضيات',
  'ماجستير علوم طبية',
  'ماجستير العلاج المهني',
  'ماجستير صيدلة',
  'ماجستير فلسفه',
  'ماجستير فيزياء',
  'ماجستير دراسات مساعد طبيب',
  'ماجستير علوم سياسية',
  'ماجستير دراسات مهنيه',
  'ماجستير إدارة شؤون العامه',
  'ماجستير شؤون عامة',
  'ماجستير صحة عامة',
  ' ماجستير إدارة عامة',
  ' ماجستير تربية اسلامية',
  'ماجستير في الأبحاث',
  'ماجستير علوم في التربية',
  'ماجستير علوم في الهندسة',
  ' ماجستير علوم في المالية',
  'ماجستير علوم في إدارة الموارد البشرية',
  'ماجستير علوم في أدارة نظم المعلومات',
  'ماجستير علوم في نظم المعلومات',
  ' ماجستير علوم في تكنولوجيا المعلومات',
  'ماجستير علوم في التمريض',
  'ماجستير علوم في أدارة المشروعات',
  'ماجستير علوم في الإدارة',
  'ماجستير علوم في القيادة والريادة',
  ' ماجستير علوم في أدارة سلسلة التوريد',
  'ماجستير علوم في التعليم',
  'ماجستير علوم إجتماعية',
  'ماجستير في الجراحه',
  'ماجستير دراسات',
  'دكتوراه في أدارة المعلومات',
  'دكتوراه في الهندسة',
  'دكتوراه في التربية والتعليم',
  'دكتوراه في الفنون',
  'دكتوراه في فن الموسيقى',
  'دكتوراه في التربية الموسيقية',
  'دكتوراه في اللغات الحديثة',
  'دكتوراه في علوم التمريض',
  'دكتوراه في الفلسفة',
  'دكتوراه في الصحة العامه',
  'دكتوراه في العلوم',
  'تخصصات دراسة أخر'
];

export const TEACHING_EXPERIENCE = [
  '1 Year',
  '2 Years',
  '3 Years',
  '4 Years',
  '5 Years',
  '6 Years',
  '7 Years',
  '8 Years',
  '9 Years',
  '10 Years',
  '10+ Years'
];

export const GRADES = [
  '1st',
  '2nd',
  '3rd',
  '4th',
  '5th',
  '6th',
  '7th',
  '8th',
  '9th',
  '10th',
  '11th',
  '12th'
];
